<div class="mask-overlay">
  <div class="mask-header">
    <span class="mask-title">Paint Mask — white areas will be regenerated by AI</span>
    <div class="mask-toolbar">
      <label for="mask-brush">Brush</label>
      <input id="mask-brush" type="range" min="5" max="80" step="1" bind:value={maskBrushSize} />
      <span class="value">{maskBrushSize}</span>
      <button class="tool-btn" onclick={clearMask}>Clear</button>
      <button class="tool-btn" onclick={fillMask}>Fill All</button>
    </div>
  </div>
  <div class="mask-canvas-container" bind:this={containerEl}>
    <canvas
      bind:this={bgCanvas}
      class="mask-bg"
      width={512}
      height={512}
    ></canvas>
    <canvas
      bind:this={maskCanvas}
      class="mask-draw"
      width={512}
      height={512}
      onpointerdown={onDown}
      onpointermove={onMove}
      onpointerup={onUp}
      onpointerleave={onUp}
    ></canvas>
  </div>
  <div class="mask-footer">
    <div class="prompt-row">
      <input
        type="text"
        class="prompt-input"
        placeholder="Describe what to generate..."
        bind:value={prompt}
        onkeydown={(e) => { if (e.key === 'Enter' && prompt.trim()) onGenerate(); }}
      />
    </div>
    <div class="mask-actions">
      <button class="action-btn cancel" onclick={onCancel}>Cancel</button>
      <button class="action-btn generate" onclick={onGenerate} disabled={!prompt.trim()}>
        Generate
      </button>
    </div>
  </div>
</div>

<script lang="ts">
  import { onMount } from "svelte";

  let {
    terrainImage,
    onSubmit,
    onClose,
  }: {
    terrainImage: Uint8Array;
    onSubmit: (mask: Uint8Array, prompt: string) => void;
    onClose: () => void;
  } = $props();

  let containerEl: HTMLElement;
  let bgCanvas: HTMLCanvasElement;
  let maskCanvas: HTMLCanvasElement;
  let maskBrushSize = $state(30);
  let prompt = $state("");
  let painting = false;

  onMount(() => {
    // Draw terrain image onto background canvas
    const bgCtx = bgCanvas.getContext("2d")!;
    const blob = new Blob([terrainImage], { type: "image/png" });
    const url = URL.createObjectURL(blob);
    const img = new Image();
    img.onload = () => {
      bgCtx.drawImage(img, 0, 0, 512, 512);
      URL.revokeObjectURL(url);
    };
    img.src = url;

    // Clear mask canvas (transparent = no mask)
    const maskCtx = maskCanvas.getContext("2d")!;
    maskCtx.clearRect(0, 0, 512, 512);
  });

  function getCanvasPos(e: PointerEvent): { x: number; y: number } {
    const rect = maskCanvas.getBoundingClientRect();
    const scaleX = 512 / rect.width;
    const scaleY = 512 / rect.height;
    return {
      x: (e.clientX - rect.left) * scaleX,
      y: (e.clientY - rect.top) * scaleY,
    };
  }

  function drawDot(x: number, y: number) {
    const ctx = maskCanvas.getContext("2d")!;
    ctx.globalCompositeOperation = "source-over";
    ctx.fillStyle = "rgba(255, 255, 255, 0.8)";
    ctx.beginPath();
    ctx.arc(x, y, maskBrushSize / 2, 0, Math.PI * 2);
    ctx.fill();
  }

  function onDown(e: PointerEvent) {
    if (e.button !== 0) return;
    painting = true;
    maskCanvas.setPointerCapture(e.pointerId);
    const pos = getCanvasPos(e);
    drawDot(pos.x, pos.y);
  }

  function onMove(e: PointerEvent) {
    if (!painting) return;
    const pos = getCanvasPos(e);
    drawDot(pos.x, pos.y);
  }

  function onUp(_e: PointerEvent) {
    painting = false;
  }

  function clearMask() {
    const ctx = maskCanvas.getContext("2d")!;
    ctx.clearRect(0, 0, 512, 512);
  }

  function fillMask() {
    const ctx = maskCanvas.getContext("2d")!;
    ctx.fillStyle = "white";
    ctx.fillRect(0, 0, 512, 512);
  }

  function getMaskPng(): Uint8Array {
    // Export mask as black/white PNG: painted areas = white, rest = black
    const ctx = maskCanvas.getContext("2d")!;
    const imageData = ctx.getImageData(0, 0, 512, 512);
    const pixels = imageData.data;

    // Create a new canvas for the final b/w mask
    const outCanvas = document.createElement("canvas");
    outCanvas.width = 512;
    outCanvas.height = 512;
    const outCtx = outCanvas.getContext("2d")!;
    const outData = outCtx.createImageData(512, 512);

    for (let i = 0; i < pixels.length; i += 4) {
      // If alpha > 0, this pixel was painted → white in mask
      const painted = pixels[i + 3] > 10 ? 255 : 0;
      outData.data[i] = painted;
      outData.data[i + 1] = painted;
      outData.data[i + 2] = painted;
      outData.data[i + 3] = 255;
    }
    outCtx.putImageData(outData, 0, 0);

    const dataUrl = outCanvas.toDataURL("image/png");
    const base64 = dataUrl.split(",")[1];
    const binaryString = atob(base64);
    const bytes = new Uint8Array(binaryString.length);
    for (let i = 0; i < binaryString.length; i++) {
      bytes[i] = binaryString.charCodeAt(i);
    }
    return bytes;
  }

  function onGenerate() {
    if (!prompt.trim()) return;
    const maskPng = getMaskPng();
    onSubmit(maskPng, prompt);
  }

  function onCancel() {
    onClose();
  }
</script>

<style>
  .mask-overlay {
    position: absolute;
    inset: 0;
    background: rgba(0, 0, 0, 0.85);
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    z-index: 100;
    padding: 16px;
  }

  .mask-header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    width: 512px;
    margin-bottom: 8px;
    gap: 12px;
  }

  .mask-title {
    font-size: 12px;
    color: var(--text-secondary);
    white-space: nowrap;
  }

  .mask-toolbar {
    display: flex;
    align-items: center;
    gap: 6px;
    font-size: 12px;
    color: var(--text-secondary);
  }

  .mask-toolbar input[type="range"] {
    width: 80px;
    accent-color: var(--accent);
  }

  .mask-toolbar .value {
    min-width: 24px;
    font-size: 11px;
    font-variant-numeric: tabular-nums;
  }

  .tool-btn {
    width: auto;
    padding: 4px 8px;
    font-size: 11px;
    margin-top: 0;
    background: var(--bg-tertiary);
    border: 1px solid var(--border);
  }

  .tool-btn:hover {
    background: var(--border);
  }

  .mask-canvas-container {
    position: relative;
    width: 512px;
    height: 512px;
    border: 1px solid var(--border);
    border-radius: 4px;
    overflow: hidden;
  }

  .mask-bg, .mask-draw {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
  }

  .mask-draw {
    cursor: crosshair;
  }

  .mask-footer {
    width: 512px;
    margin-top: 8px;
  }

  .prompt-row {
    margin-bottom: 8px;
  }

  .prompt-input {
    width: 100%;
    padding: 8px 10px;
    background: var(--bg-tertiary);
    color: var(--text-primary);
    border: 1px solid var(--border);
    border-radius: 4px;
    font-size: 13px;
    outline: none;
  }

  .prompt-input:focus {
    border-color: var(--accent);
  }

  .prompt-input::placeholder {
    color: var(--text-secondary);
  }

  .mask-actions {
    display: flex;
    gap: 8px;
  }

  .action-btn {
    flex: 1;
    padding: 8px;
    font-size: 13px;
    margin-top: 0;
  }

  .action-btn.cancel {
    background: var(--bg-tertiary);
    border: 1px solid var(--border);
  }

  .action-btn.cancel:hover {
    background: var(--border);
  }

  .action-btn.generate {
    background: var(--accent);
  }

  .action-btn.generate:disabled {
    opacity: 0.4;
  }
</style>
